"""posts table

Revision ID: 04c59df74853
Revises: 36a3c0a1a2be
Create Date: 2020-05-09 15:54:36.291811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c59df74853'
down_revision = '36a3c0a1a2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'post', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answer', type_='foreignkey')
    op.create_foreign_key(None, 'answer', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
